### ISSUE TITLE
Program won't run

### ISSUE THREAD

**Issue by eagleofdeath13** [tommaier123/NoodleManager#5]
I'm trying to run the program on Windows (and i tried from 2 different computers), the cursor change to the loading icon, than, nothing, i tried to run it as administrator, doesn't work either.
I don't see any pre-requisites somewhere, so i don't know what i can be doing wrong, i also didn't find any logg file i could use to check the error.
(I'm on the latest version)

**Comment by TheStap** [comment]
same for me, win 10 home

**Comment by jsaunders92** [comment]
Hi, I was having the same issue as well. I had a quick look at the code and there's a minor error. 
https://github.com/tommaier123/NoodleManager/blob/master/NoodleManager/Form1.cs#L126

```
string applicationLocation = System.Reflection.Assembly.GetEntryAssembly().Location;
applicationLocation = Path.GetDirectoryName(applicationLocation);
string dirLocation = Path.GetDirectoryName(applicationLocation);
```

`dirLocation` is getting the directory name of the `applicationLocation` which is now the directory name of `applicationLocation`

So for me, I had a folder in Documents called NoodleManagerRelease and its created a folder in Documents called NoodleManagerUpdate where the files were downloaded to. If I get some time later I'll see if I can make the change. I suppose what makes the most sense is for updates to be extracted into the same folder.

**Comment by tommaier123** [comment]
The program not starting is an issue in 1.3.9 for that reason I have set it to prerelease for now. I believe it has something to do with the certificates since there is no error message.
I believe the code is correct like this. applicationLocation is the directory the executable is in and dirLocation is the directory that contains that directory. If its not starting that shouldnt have anything to do with the update functionality anyways.
Thanks for reporting the issue though. I am working on an update at the moment to fix a bunch of stuff.
Sorry, I should really check the issues more often.

**Comment by tommaier123** [comment]
1.4.0 solves the not starting issues.
